{% set name = "amostra" %}
{% set version = "0.2.4" %}
{% set sha256 = "ec5cf014b081b2c62e0dd884ae84579a24594219141a85964c8732657f62198c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - doct
    - jsonschema
    - mongoquery
    - pymongo
    - pyyaml
    - requests
    - tornado
    - ujson

test:
  imports:
    - amostra

about:
  home: https://nsls-ii.github.io/amostra
  license: BSD-3-Clause
  license_file: LICENSE
  summary: This is a classic version (v0.2.x branch) of amostra that is a collection of light-weight sample management classes
  dev_url: https://github.com/NSLS-II/amostra/tree/v0.2.x
  doc_url: https://nsls-ii.github.io/amostra

extra:
  recipe-maintainers:
    - JunAishima
    - mrakitin
    - conda-forge/event-model
