{% set name = "amostra" %}
{% set version = "0.2.3" %}
{% set sha256 = "398c07b3edf20eef5293db65b7843376151d4be5602e1063a1c9c257eb7dac4c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - doct
    - jsonschema
    - mongoquery
    - pymongo
    - pyyaml
    - requests
    - tornado
    - ujson

test:
  imports:
    - amostra

about:
  home: https://nsls-ii.github.io/amostra
  license: BSD-3-Clause
  license_file: LICENSE
  summary: This is a classic version (v0.2.x branch) of amostra that is a collection of light-weight sample management classes
  dev_url: https://github.com/NSLS-II/amostra/tree/v0.2.x
  doc_url: https://nsls-ii.github.io/amostra

extra:
  recipe-maintainers:
    - JunAishima
    - mrakitin
    - conda-forge/event-model
