{% set name = "amostra" %}
{% set version = "0.2" %}
{% set sha256 = "d0e96cb85614474fde40d1cc9623f9b0a03ab58bd7a2e82be9d5cf3fb87084bf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - doct
    - jsonschema
    - mongoquery
    - pymongo
    - pyyaml
    - requests
    - tornado
    - ujson

test:
  imports:
    - amostra

about:
  home: https://nsls-ii.github.io/amostra
  license: BSD-3-Clause
  license_file: LICENSE
  summary: amostra is a collection of light-weight sample management classes
  dev_url: https://github.com/NSLS-II/amostra
  doc_url: https://nsls-ii.github.io/amostra

extra:
  recipe-maintainers:
    - mrakitin
    - conda-forge/event-model
